### ISSUE TITLE
Minter should default to founder on LATToken creation

### ISSUE THREAD

**Issue by IsaacPayne** [BlockchainLabsNZ/LAToken-Contracts-Audit#19]
Similar to how `founder` is set to `msg.sender` on `LATToken` creation, `minter` should be set to `msg.sender`

**Comment by matt-lough** [comment]
Minter should be the contract address, not msg.sender

**Comment by matt-lough** [comment]
A potential "fix" could be to have an argument to set the minter and exchanger on contract creation

**Comment by ElKornacio** [comment]
Both minter and exchanger are deployed after token deployment, so it's not very reasonable to add this arguments to a token constructor. Can we close this issue?)
