### ISSUE TITLE
Add check for if teamPoolForFrozenTokens has been set

### ISSUE THREAD

**Issue by OperationNine** [BlockchainLabsNZ/LAToken-Contracts-Audit#22]
There is no check if `teamPoolForFrozenTokens` has been set resulting in dangerously being able to mint these tokens into nowhere

https://github.com/BlockchainLabsNZ/LAToken-Contracts-Audit/blob/master/contracts/LATokenMinter.sol

**Comment by matt-lough** [comment]
Fixed https://github.com/BlockchainLabsNZ/LAToken-Contracts-Audit/pull/40/files
